name: On PR Open
run-name: on-pr-open

# Runs on every change in a pull request, even draft requests
on:
  pull_request:

# Cancel any existing runs if new code is pushed to avoid multiple simultaneous instances
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Required for Nx affected runs (not in use in this repo, but kept for completeness)

      # Publish the dist folder so that it can be picked up by another job
      - name: Publish dist artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist
          retention-days: 1